### ISSUE TITLE
Some items show upgrades which arent there

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/Bug-Reports#17] opened 2017-06-04 07:45 UTC
Lotus orb and battlefury show there to be upgrades on the image and some others i cant remember.

**Comment by ProstoSanja** [comment] 2017-08-12 07:15
Both described items have 5 upgrades, as they should...

**Comment by Trildar** [comment] 2018-01-24 03:45
I think this was caused by extraneous level values in KV. Should be fixed.

**Closed as completed by Trildar** 2018-01-24 03:45 UTC
