### ISSUE TITLE
"Farming Core becomes locked and unusable when Greater Arcane Boots are dissasembled

### ISSUE THREAD

**Issue by ValkyGr** [AngelArenaAllstars/Bug-Reports#36] opened 2017-06-25 14:44 UTC
Today while playing a game with tidehunter i bought greater arcane boots and then wanted to dissasemble them to buy greater guardian graves. When i dissasembled my arcane boots, my farming core got locked for combining and became unusable and as you cant right click on cores i was unable to unlock combining. Tried disconnectiong and reconnecting to see if it would fix the issues but my core was still locked. 
The bug can be reproduced as i tried reproducing it in a solo lobby with cheats enabled to quicky cheat in a few farming cores.

**Comment by ProstoSanja** [comment] 2017-08-17 20:05
Probably fixed

**Comment by Trildar** [comment] 2018-01-24 04:27
Duplicate of #23.

**Closed as completed by Trildar** 2018-01-24 04:27 UTC
